//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "faritany_point")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub utilisateur_id: i32,
    pub room_id: i32,
    pub coord: String,
    pub date_creation: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::faritany_room::Entity",
        from = "Column::RoomId",
        to = "super::faritany_room::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    FaritanyRoom,
    #[sea_orm(
        belongs_to = "super::utilisateur::Entity",
        from = "Column::UtilisateurId",
        to = "super::utilisateur::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Utilisateur,
}

impl Related<super::faritany_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FaritanyRoom.def()
    }
}

impl Related<super::utilisateur::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Utilisateur.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
