//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "faritany_room")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub uuid: String,
    pub password: Option<String>,
    pub taille: String,
    pub reflexion: i32,
    pub date_creation: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::faritany_point::Entity")]
    FaritanyPoint,
    #[sea_orm(has_many = "super::faritany_room_utilisateur::Entity")]
    FaritanyRoomUtilisateur,
}

impl Related<super::faritany_point::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FaritanyPoint.def()
    }
}

impl Related<super::faritany_room_utilisateur::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FaritanyRoomUtilisateur.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
