//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub use super::faritany_point::Entity as FaritanyPoint;
pub use super::faritany_room::Entity as FaritanyRoom;
pub use super::faritany_room_utilisateur::Entity as FaritanyRoomUtilisateur;
pub use super::utilisateur::Entity as Utilisateur;
